In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Inventors_1975-2010 part 2.csv')

In [4]:
df.head()

Unnamed: 0   patent  firstname  lastname street      city state country   
0           0  6100132    TSUTOMU      SATO    NaN  YOKOHAMA   NaN      JP  \
1           1  6100133     STEFAN    NYGREN    NaN   UPPSALA   NaN      SE   
2           2  6100133       HANS  NORSTROM    NaN     SOLNA   NaN      SE   
3           3  6100134  YOSHIKAZU      OHNO    NaN     TOKYO   NaN      JP   
4           4  6100135   SHYE LIN        WU    NaN   HSINCHU   NaN      TW   

  zipcode nationality  invseq  
0     NaN         NaN       1  
1     NaN         NaN       2  
2     NaN         NaN       1  
3     NaN         NaN       1  
4     NaN         NaN       1

In [5]:
df.shape

(4396021, 11)

In [6]:
df.isnull().sum()

Unnamed: 0           0
patent               0
firstname          233
lastname           100
street         4277294
city               206
state          2194325
country             33
zipcode        4215480
nationality    1772876
invseq               0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4396021 entries, 0 to 4396020
Data columns (total 11 columns):
 #   Column       Dtype 
---  ------       ----- 
 0   Unnamed: 0   int64 
 1   patent       int64 
 2   firstname    object
 3   lastname     object
 4   street       object
 5   city         object
 6   state        object
 7   country      object
 8   zipcode      object
 9   nationality  object
 10  invseq       int64 
dtypes: int64(3), object(8)
memory usage: 368.9+ MB


In [8]:
df.drop(columns=['Unnamed: 0',], axis=1, inplace=True)

In [9]:
df.head()

patent  firstname  lastname street      city state country zipcode   
0  6100132    TSUTOMU      SATO    NaN  YOKOHAMA   NaN      JP     NaN  \
1  6100133     STEFAN    NYGREN    NaN   UPPSALA   NaN      SE     NaN   
2  6100133       HANS  NORSTROM    NaN     SOLNA   NaN      SE     NaN   
3  6100134  YOSHIKAZU      OHNO    NaN     TOKYO   NaN      JP     NaN   
4  6100135   SHYE LIN        WU    NaN   HSINCHU   NaN      TW     NaN   

  nationality  invseq  
0         NaN       1  
1         NaN       2  
2         NaN       1  
3         NaN       1  
4         NaN       1

In [10]:
df['patent'].value_counts()

patent
7581231    76
7512957    60
7555757    51
7013469    51
7017162    51
           ..
6936899     1
6936900     1
6936901     1
6936905     1
6980584     1
Name: count, Length: 1754920, dtype: int64

In [11]:
df['patent'].nunique()

1754920

In [12]:
df['patent'].unique().tolist()

[6100132,
 6100133,
 6100134,
 6100135,
 6100136,
 6100137,
 6100138,
 6100139,
 6100140,
 6100141,
 6100142,
 6100143,
 6100144,
 6100145,
 6100146,
 6100147,
 6100148,
 6100149,
 6100150,
 6100151,
 6100152,
 6100153,
 6100154,
 6100155,
 6100156,
 6100157,
 6100158,
 6100159,
 6100160,
 6100161,
 6100162,
 6100163,
 6100164,
 6100165,
 6100166,
 6100167,
 6100168,
 6100169,
 6100170,
 6100171,
 6100172,
 6100173,
 6100174,
 6100175,
 6100176,
 6100177,
 6100178,
 6100179,
 6100180,
 6100181,
 6100182,
 6100183,
 6100184,
 6100185,
 6100186,
 6100187,
 6100188,
 6100189,
 6100190,
 6100191,
 6100192,
 6100193,
 6100194,
 6100195,
 6100196,
 6100197,
 6100198,
 6100199,
 6100200,
 6100201,
 6100202,
 6100203,
 6100204,
 6100205,
 6100206,
 6100207,
 6100208,
 6100209,
 6100210,
 6100211,
 6100212,
 6100213,
 6100214,
 6100215,
 6100216,
 6100217,
 6100218,
 6100219,
 6100220,
 6100221,
 6100222,
 6100223,
 6100224,
 6100225,
 6100226,
 6100227,
 6100228,
 6100229,
 6100230,
 6100231,


In [13]:
a = df['patent'].isnull().values.any()

In [14]:
a

False

In [15]:
b= df['firstname'].isnull().values.any()

In [16]:
b

True

In [17]:
df['firstname'].fillna(value= "Unspecified", inplace=True)

In [18]:
c = df['lastname'].isnull().values.any()

In [19]:
c

True

In [20]:
df['lastname'].fillna(value= "Unspecified", inplace=True)

In [21]:
df['street'].value_counts()

street
2185 S. Larsen Pkwy.                494
235 Chung-Ho Box 8-24               254
Argestrasse 19                      123
P.O. Box 90                          79
58, Ma Yuan West St.                 79
                                   ... 
13F, No. 232, Sec. 3, Ba-De Road      1
6699 Via Estrada, 6                   1
14706 High Valley Rd.                 1
Samjeong-dong, Ojeong-gu              1
5384 Monarch Pine La.                 1
Name: count, Length: 89848, dtype: int64

In [22]:
df['street'].nunique()

89848

In [23]:
df['street'].unique()

array([nan, '146 Bentwood Cir.', '602 West State St.', ..., 'ul. Lea 151',
       '1510 Cumberland Ct.', '5384 Monarch Pine La.'], dtype=object)

In [24]:
df['street'].fillna(value= "Unspecified", inplace=True)

In [25]:
d = df['city'].isnull().values.any()

In [26]:
d

True

In [27]:
df['city'].unique()

array(['YOKOHAMA', 'UPPSALA', 'SOLNA', ..., '43-187 Orzesze',
       '30-133 Krakow', 'Golden Bridges'], dtype=object)

In [28]:
df['city'].fillna(value= "UN SPECIFIED", inplace=True)

In [29]:
df['state'].unique()

array([nan, 'VT', 'ID', 'CA', 'TX', 'NC', 'NY', 'OR', 'MI', 'CT', 'MN',
       'TN', 'GA', 'NV', 'DE', 'PA', 'WV', 'IL', 'OK', 'LA', 'NJ', 'VA',
       'OH', 'KS', 'MA', 'CO', 'WA', 'FL', 'IN', 'MO', 'NE', 'RI', 'MD',
       'WI', 'IA', 'UT', 'SC', 'KY', 'AR', 'NH', 'AZ', 'NM', 'MS', 'ME',
       'DC', 'AL', 'MT', 'ND', 'SD', 'HI', 'WY', 'PR', 'AK', 'VI', 'GU',
       'MH'], dtype=object)

In [30]:
df['state'].nunique()

55

In [31]:
e = df['state'].isnull().values.any()

In [32]:
e

True

In [33]:
df['state'].fillna(value= "UN", inplace=True)

In [34]:
f = df['country'].isnull().values.any()

In [35]:
f

True

In [36]:
df['country'].nunique()

191

In [37]:
df['country'].unique()

array(['JP', 'SE', 'TW', 'US', 'DE', 'KR', 'NL', 'SG', 'HK', 'MY', 'IT',
       'GB', 'FR', 'BE', 'DK', 'CZ', 'CN', 'CH', 'CA', 'ES', 'AR', 'RU',
       'IL', 'HR', 'ZA', 'GT', 'NZ', 'IE', 'TH', 'AT', 'IN', 'FI', 'AU',
       'NO', 'GR', 'LU', 'SI', 'PA', 'BR', 'CL', 'LI', 'BS', 'MX', 'CO',
       'SK', 'HU', 'MA', 'AN', 'BO', 'RO', 'SA', 'KY', 'PT', 'CR', 'BY',
       'BH', 'PL', 'VE', 'MC', 'YU', 'DZ', 'IS', 'SU', 'TR', 'ML', 'AW',
       'KW', 'JM', 'UA', 'HN', 'TC', 'LV', 'GE', 'EG', 'PH', 'PK', 'VN',
       'GI', 'DO', 'IR', 'SY', 'DD', 'EE', 'BM', 'CS', 'ID', 'GA', 'KE',
       'PE', 'AE', 'LB', 'KG', 'CU', 'UY', 'KZ', 'MD', 'LY', 'SN', 'JO',
       'SV', 'EC', nan, 'BG', 'AM', 'KN', 'MG', 'SR', 'UZ', 'MT', 'LT',
       'BD', 'MK', 'BA', 'AG', 'UG', 'ZW', 'PF', 'TK', 'TT', 'CY', 'KP',
       'NR', 'TZ', 'NE', 'LK', 'VI', 'GY', 'NG', 'YE', 'BB', 'TN', 'AD',
       'SL', 'FJ', 'CM', 'OM', 'VG', 'MO', 'PG', 'XH', 'AI', 'OA', 'SZ',
       'GC', 'NF', 'CG', 'CX', 'NI', 'AZ', 'BN', 'PW

In [38]:
df['country'].fillna(value= "UN", inplace=True)

In [39]:
df['zipcode'].nunique()

43073

In [40]:
df['zipcode'].unique().tolist()

[nan,
 11787.0,
 33176.0,
 11777.0,
 33156.0,
 11733.0,
 11790.0,
 33308.0,
 27023.0,
 27105.0,
 27106.0,
 62223.0,
 70816.0,
 70739.0,
 45002.0,
 46616.0,
 64137.0,
 2537.0,
 83835.0,
 43231.0,
 19808.0,
 29020.0,
 60018.0,
 21045.0,
 21044.0,
 49036.0,
 46819.0,
 52803.0,
 33923.0,
 19073.0,
 78133.0,
 78756.0,
 97125.0,
 90505.0,
 91360.0,
 11729.0,
 44280.0,
 10989.0,
 50158.0,
 99205.0,
 95129.0,
 3301.0,
 1007.0,
 95060.0,
 92807.0,
 34997.0,
 92630.0,
 92653.0,
 94618.0,
 94708.0,
 48183.0,
 48336.0,
 48307.0,
 48105.0,
 19063.0,
 55123.0,
 55112.0,
 94025.0,
 6378.0,
 6357.0,
 2808.0,
 34685.0,
 95051.0,
 78751.0,
 78610.0,
 7945.0,
 90250.0,
 11795.0,
 30067.0,
 33010.0,
 15206.0,
 70122.0,
 80403.0,
 48118.0,
 95014.0,
 60187.0,
 33131.0,
 22301.0,
 20910.0,
 22209.0,
 1754.0,
 1450.0,
 1863.0,
 12144.0,
 1775.0,
 3051.0,
 1532.0,
 2154.0,
 48706.0,
 19320.0,
 63124.0,
 97202.0,
 33614.0,
 6053.0,
 33408.0,
 83647.0,
 44094.0,
 89191.0,
 91344.0,
 46033.0,
 21043.0,
 7760.0,


In [41]:
df['zipcode'] = pd.to_numeric(df['zipcode'], errors='coerce').fillna(0, downcast='infer')

In [42]:
df['zipcode'] = df['zipcode'].astype(int)

In [43]:
df['zipcode'].mean()      

2508.230986385188

In [44]:
df['zipcode'] = df['zipcode'].replace(0, 25082)  

In [45]:
df['nationality'].value_counts()

nationality
US    1306948
JP     567688
DE     159604
KR     119061
TW      80705
       ...   
SB          1
GL          1
PF          1
AX          1
NC          1
Name: count, Length: 172, dtype: int64

In [46]:
df['nationality'].nunique()

172

In [47]:
df['nationality'].unique()

array([nan, 'US', 'CA', 'GB', 'TW', 'NZ', 'KR', 'HK', 'CN', 'DE', 'ZA',
       'BE', 'JP', 'ES', 'IT', 'CH', 'FR', 'CZ', 'MC', 'SE', 'IL', 'FI',
       'BS', 'AU', 'NL', 'NO', 'AT', 'MX', 'TH', 'LU', 'IE', 'DK', 'VE',
       'MY', 'IN', 'TR', 'SG', 'BR', 'HU', 'RU', 'SI', 'RO', 'GR', 'AE',
       'LI', 'PT', 'EG', 'UA', 'BG', 'BY', 'IS', 'AR', 'VG', 'HR', 'CO',
       'ID', 'MA', 'PL', 'IR', 'CS', 'SA', 'PH', 'MG', 'VN', 'AD', 'ML',
       'CL', 'BM', 'TC', 'PK', 'SK', 'NE', 'LV', 'GT', 'LT', 'UY', 'KP',
       'GE', 'SV', 'YU', 'KE', 'LB', 'EC', 'PE', 'CY', 'EE', 'VA', 'BO',
       'KZ', 'AP', 'CU', 'CR', 'ZW', 'MD', 'KW', 'LK', 'AM', 'DO', 'MP',
       'JM', 'AN', 'MT', 'KY', 'JO', 'ET', 'NR', 'TN', 'TK', 'OM', 'KN',
       'NG', 'BD', 'TT', 'GH', 'MO', 'GF', 'QA', 'DM', 'ZM', 'DZ', 'AZ',
       'SY', 'IO', 'PY', 'UZ', 'BB', 'KH', 'HN', 'FJ', 'SC', 'GI', 'BJ',
       'BA', 'GA', 'CM', 'UG', 'ME', 'AG', 'BF', 'TD', 'TJ', 'USA', 'RW',
       'PA', 'IQ', 'IM', 'GM', 'KG', 'SB', 'GL', 'P

In [48]:
df['nationality'].fillna(value= "UN", inplace=True)

In [49]:
df['invseq'].value_counts()

invseq
1     1403369
0     1020691
2      866149
3      499617
4      270412
       ...   
72          1
68          1
73          1
67          1
75          1
Name: count, Length: 76, dtype: int64

In [50]:
df['invseq'].nunique()

76

In [51]:
df['invseq'].unique()

array([ 1,  2,  3,  4,  6,  5,  7,  9,  8, 10, 11, 18, 20, 16, 17, 13, 14,
       24, 25, 12, 21, 23, 15, 22, 19, 26, 27, 28, 29, 30, 32, 31, 38, 33,
       40, 39, 37, 36, 34, 41, 35,  0, 49, 42, 44, 47, 46, 45, 48, 50, 43,
       58, 55, 51, 59, 54, 56, 52, 57, 53, 67, 73, 68, 72, 61, 60, 71, 63,
       69, 65, 62, 70, 64, 66, 74, 75], dtype=int64)

In [52]:
x = df['invseq'].isnull().values.any()

In [53]:
x

False

In [54]:
df.isnull().sum()

patent         0
firstname      0
lastname       0
street         0
city           0
state          0
country        0
zipcode        0
nationality    0
invseq         0
dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4396021 entries, 0 to 4396020
Data columns (total 10 columns):
 #   Column       Dtype 
---  ------       ----- 
 0   patent       int64 
 1   firstname    object
 2   lastname     object
 3   street       object
 4   city         object
 5   state        object
 6   country      object
 7   zipcode      int32 
 8   nationality  object
 9   invseq       int64 
dtypes: int32(1), int64(2), object(7)
memory usage: 318.6+ MB


In [56]:
df.to_csv('Inventors_2.csv')