In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Assignees_1975-2010.csv')

In [4]:
df.head()

Unnamed: 0   patent  asgtype                        assignee city state   
0           0  3858241      6.0  UNITED STATES OF AMERICA, ARMY  NaN   NaN  \
1           1  3858242      1.0                             NaN  NaN   NaN   
2           2  3858243      3.0                        PLYMATIC  NaN   NaN   
3           3  3858244      1.0                             NaN  NaN   NaN   
4           4  3858245      2.0                 HAIR AGAIN LTD.  NaN   NaN   

  country  nationality  residence  asgseq  
0     NaN          NaN        NaN       0  
1     NaN          NaN        NaN       0  
2     NaN          NaN        NaN       0  
3     NaN          NaN        NaN       0  
4     NaN          NaN        NaN       0

In [5]:
df.shape

(3755526, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3755526 entries, 0 to 3755525
Data columns (total 10 columns):
 #   Column       Dtype  
---  ------       -----  
 0   Unnamed: 0   int64  
 1   patent       int64  
 2   asgtype      float64
 3   assignee     object 
 4   city         object 
 5   state        object 
 6   country      object 
 7   nationality  float64
 8   residence    float64
 9   asgseq       int64  
dtypes: float64(3), int64(3), object(4)
memory usage: 286.5+ MB


In [7]:
#sns.heatmap(df.isnull(), cbar=True)

In [8]:
df.drop(columns=['Unnamed: 0', 'nationality','residence'], axis=1, inplace=True)

In [9]:
df.head()

patent  asgtype                        assignee city state country  asgseq
0  3858241      6.0  UNITED STATES OF AMERICA, ARMY  NaN   NaN     NaN       0
1  3858242      1.0                             NaN  NaN   NaN     NaN       0
2  3858243      3.0                        PLYMATIC  NaN   NaN     NaN       0
3  3858244      1.0                             NaN  NaN   NaN     NaN       0
4  3858245      2.0                 HAIR AGAIN LTD.  NaN   NaN     NaN       0

In [10]:
df['patent'].value_counts()

patent
3858241    1
6484597    1
6484599    1
6484600    1
6484602    1
          ..
5112083    1
5112084    1
5112085    1
5112086    1
7861316    1
Name: count, Length: 3755526, dtype: int64

In [11]:
df['patent'].nunique()

3755526

In [12]:
df['patent'].unique()

array([3858241, 3858242, 3858243, ..., 7861314, 7861315, 7861316],
      dtype=int64)

In [13]:
df['asgtype'].value_counts()

asgtype
2.0     1762533
3.0     1591868
1.0      326014
6.0       36496
4.0       14923
7.0        9392
5.0        7385
0.0        6619
14.0         82
13.0         67
12.0         66
9.0          54
15.0         20
8.0           4
16.0          1
Name: count, dtype: int64

In [14]:
df['asgtype'].nunique()

15

In [15]:
df['asgtype'].unique()

array([ 6.,  1.,  3.,  2.,  4.,  5.,  7., 14., 13., 12.,  9., 15., 16.,
        8., nan,  0.])

In [16]:
mean_value=df['asgtype'].mean()

df['asgtype'].fillna(value=mean_value, inplace=True)

In [17]:
df['asgtype'].unique()

array([ 6.       ,  1.       ,  3.       ,  2.       ,  4.       ,
        5.       ,  7.       , 14.       , 13.       , 12.       ,
        9.       , 15.       , 16.       ,  8.       ,  2.3995762,
        0.       ])

In [18]:
df['asgtype'].nunique()

16

In [19]:
df['assignee'].value_counts()

assignee
INTERNATIONAL BUSINESS MACHINES CORPORATION    37557
CANON KABUSHIKI KAISHA                         27723
GENERAL ELECTRIC COMPANY                       24620
International Business Machines Corporation    24225
NEC CORPORATION                                19566
                                               ...  
J. R. SHORT MILLING COMPANY                        1
SIGMA COATINGS FARBEN- UND LACKWERKE GMBH          1
MOUNTAIN DEVELPOMENT                               1
SIKA AG, VORM. KASPER WINKLER & CO.                1
Kurzweil Educational Systems, Inc.                 1
Name: count, Length: 374194, dtype: int64

In [20]:
df['assignee'].nunique()

374194

In [21]:
df['assignee'].unique()

array(['UNITED STATES OF AMERICA, ARMY', nan, 'PLYMATIC', ...,
       'Goldpocket Interactive', 'Symantec Software Corporation',
       'Kurzweil Educational Systems, Inc.'], dtype=object)

In [22]:
df['assignee'].fillna(value="Unspecified", inplace=True)

In [23]:
df['assignee'].unique()

array(['UNITED STATES OF AMERICA, ARMY', 'Unspecified', 'PLYMATIC', ...,
       'Goldpocket Interactive', 'Symantec Software Corporation',
       'Kurzweil Educational Systems, Inc.'], dtype=object)

In [24]:
df['city'].value_counts()

city
TOKYO               113828
Tokyo               112817
OSAKA                27447
Osaka                25520
Armonk               24561
                     ...  
BREVIK                   1
BIBERACH AM RISS         1
JEPPO                    1
TORISDORF                1
Balbriggan               1
Name: count, Length: 46988, dtype: int64

In [25]:
df['city'].unique()

array([nan, 'MINNEAPOLIS', 'STOUGHTON', ..., 'Seabrook', 'North Gratton',
       'Balbriggan'], dtype=object)

In [26]:
df['city'].unique()

array([nan, 'MINNEAPOLIS', 'STOUGHTON', ..., 'Seabrook', 'North Gratton',
       'Balbriggan'], dtype=object)

In [27]:
df['city'].fillna(value="Unspecified", inplace=True)

In [28]:
df['state'].value_counts()

state
CA    229230
NY    106968
TX     69689
NJ     48938
IL     48804
MI     44408
MA     41440
OH     33793
MN     29842
WA     28705
PA     28301
CT     26931
DE     19874
ID     19311
FL     16942
WI     16289
NC     13667
DC     12115
CO     11090
MD     10347
GA     10024
IN     10002
VA      9088
MO      8788
OR      7032
NV      6977
AZ      6540
IA      6482
TN      5942
UT      5548
KY      3969
NH      3904
OK      3857
SC      3742
KS      3573
NM      2620
AL      2324
RI      2053
LA      1730
NE      1602
ME      1136
AR       997
MS       780
VT       756
MT       718
SD       456
WV       433
WY       366
HI       357
ND       298
AK       158
PR       101
VI        46
GU         1
JP         1
MH         1
al         1
Name: count, dtype: int64

In [29]:
df['state'].nunique()

57

In [30]:
df['state'].unique()

array([nan, 'MN', 'MA', 'CT', 'OH', 'CA', 'IL', 'PA', 'MO', 'WI', 'NY',
       'CO', 'MI', 'OK', 'OR', 'WA', 'IA', 'DE', 'FL', 'NJ', 'IN', 'GA',
       'TX', 'SC', 'NH', 'TN', 'NC', 'ID', 'UT', 'MD', 'KY', 'KS', 'VA',
       'DC', 'AZ', 'NV', 'NM', 'AL', 'HI', 'ME', 'NE', 'RI', 'MS', 'LA',
       'AR', 'VT', 'MT', 'WV', 'AK', 'SD', 'WY', 'ND', 'PR', 'GU', 'VI',
       'JP', 'MH', 'al'], dtype=object)

In [31]:
df['state'].fillna(value="UN", inplace=True)

In [32]:
df['country'].value_counts()

country
US    464042
JP    444645
DE    117683
KR     68494
TW     55919
       ...  
GP         1
KG         1
IQ         1
LK         1
GN         1
Name: count, Length: 170, dtype: int64

In [33]:
df['country'].nunique()

170

In [34]:
df['country'].unique()

array([nan, 'SE', 'CA', 'DE', 'GB', 'FR', 'JP', 'CH', 'KR', 'IT', 'AT',
       'BS', 'IL', 'FI', 'NL', 'AU', 'ZA', 'TW', 'ES', 'BR', 'IE', 'PA',
       'LI', 'HK', 'DK', 'NO', 'BE', 'UY', 'VG', 'SG', 'AN', 'RU', 'MX',
       'KY', 'HU', 'VE', 'CN', 'NZ', 'LU', 'PL', 'CL', 'CZ', 'BY', 'CU',
       'SI', 'IN', 'BM', 'IS', 'PT', 'GT', 'HR', 'PR', 'BB', 'UA', 'GI',
       'SA', 'TH', 'KN', 'US', 'AR', 'MC', 'LV', 'KW', 'SM', 'TC', 'CK',
       'VI', 'CS', 'MY', 'GU', 'MA', 'GR', 'NG', 'BZ', 'CY', 'SK', 'SU',
       'PK', 'PE', 'KP', 'RO', 'BG', 'CO', 'SZ', 'JO', 'AZ', 'EC', 'TR',
       'LT', 'CR', 'DD', 'BH', 'GE', 'VU', 'ID', 'LR', 'IR', 'AM', 'HN',
       'PG', 'NR', 'BD', 'MT', 'NE', 'PH', 'AI', 'EG', 'EE', 'KG', 'NC',
       'MU', 'SN', 'SV', 'TM', 'NP', 'BA', 'PF', 'TT', 'MG', 'LK', 'XH',
       'BV', 'BI', 'GC', 'BO', 'AE', 'AD', 'GH', 'LC', 'TV', 'SC', 'CI',
       'CV', 'AW', 'DM', 'SL', 'MK', 'LB', 'PN', 'TK', 'GP', 'TN', 'IO',
       'IQ', 'FK', 'ML', 'AG', 'CM', 'unknown', 'KM'

In [35]:
df['country'].fillna(value="UN", inplace=True)

In [36]:
df['country'] = df['country'].replace('unknown', 'UN')

In [37]:
df['country'].unique()

array(['UN', 'SE', 'CA', 'DE', 'GB', 'FR', 'JP', 'CH', 'KR', 'IT', 'AT',
       'BS', 'IL', 'FI', 'NL', 'AU', 'ZA', 'TW', 'ES', 'BR', 'IE', 'PA',
       'LI', 'HK', 'DK', 'NO', 'BE', 'UY', 'VG', 'SG', 'AN', 'RU', 'MX',
       'KY', 'HU', 'VE', 'CN', 'NZ', 'LU', 'PL', 'CL', 'CZ', 'BY', 'CU',
       'SI', 'IN', 'BM', 'IS', 'PT', 'GT', 'HR', 'PR', 'BB', 'UA', 'GI',
       'SA', 'TH', 'KN', 'US', 'AR', 'MC', 'LV', 'KW', 'SM', 'TC', 'CK',
       'VI', 'CS', 'MY', 'GU', 'MA', 'GR', 'NG', 'BZ', 'CY', 'SK', 'SU',
       'PK', 'PE', 'KP', 'RO', 'BG', 'CO', 'SZ', 'JO', 'AZ', 'EC', 'TR',
       'LT', 'CR', 'DD', 'BH', 'GE', 'VU', 'ID', 'LR', 'IR', 'AM', 'HN',
       'PG', 'NR', 'BD', 'MT', 'NE', 'PH', 'AI', 'EG', 'EE', 'KG', 'NC',
       'MU', 'SN', 'SV', 'TM', 'NP', 'BA', 'PF', 'TT', 'MG', 'LK', 'XH',
       'BV', 'BI', 'GC', 'BO', 'AE', 'AD', 'GH', 'LC', 'TV', 'SC', 'CI',
       'CV', 'AW', 'DM', 'SL', 'MK', 'LB', 'PN', 'TK', 'GP', 'TN', 'IO',
       'IQ', 'FK', 'ML', 'AG', 'CM', 'KM', 'KZ', 'M

In [38]:
df['asgseq'].value_counts()

asgseq
0     3727397
1       26297
2        1508
3         202
4          60
5          23
6          11
9          10
8           7
7           4
12          3
11          2
10          2
Name: count, dtype: int64

In [39]:
df['asgseq'].nunique()

13

In [40]:
df['asgseq'].unique()

array([ 0,  1,  2,  3,  4,  5,  7, 11,  8,  6,  9, 12, 10], dtype=int64)

In [41]:
#sns.heatmap(df.isnull(), cbar=True)

In [42]:
df.head()

patent  asgtype                        assignee         city state   
0  3858241      6.0  UNITED STATES OF AMERICA, ARMY  Unspecified    UN  \
1  3858242      1.0                     Unspecified  Unspecified    UN   
2  3858243      3.0                        PLYMATIC  Unspecified    UN   
3  3858244      1.0                     Unspecified  Unspecified    UN   
4  3858245      2.0                 HAIR AGAIN LTD.  Unspecified    UN   

  country  asgseq  
0      UN       0  
1      UN       0  
2      UN       0  
3      UN       0  
4      UN       0

In [43]:
df.columns

Index(['patent', 'asgtype', 'assignee', 'city', 'state', 'country', 'asgseq'], dtype='object')

In [44]:
df.to_csv('Assignees.csv')