In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Citations_2000-2010 part 1.csv')

In [4]:
df.head()

Unnamed: 0   patent   citation    cit_date      cit_name cit_kind   
0           0  6009555  4192017.0  1980-03-01           FAY      NaN  \
1           1  6009555  4547903.0  1985-10-01  BROWN ET AL.      NaN   
2           2  6009555  4768231.0  1988-09-01       SCHRACK      NaN   
3           3  6009555  4951316.0  1990-08-01         MOODY      NaN   
4           4  6009555  5105475.0  1992-04-01   LYND ET AL.      NaN   

  cit_country category  citseq  obsnum  
0         NaN      NaN     NaN     1.0  
1         NaN      NaN     NaN     2.0  
2         NaN      NaN     NaN     3.0  
3         NaN      NaN     NaN     4.0  
4         NaN      NaN     NaN     5.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14000000 entries, 0 to 13999999
Data columns (total 10 columns):
 #   Column       Dtype  
---  ------       -----  
 0   Unnamed: 0   int64  
 1   patent       int64  
 2   citation     float64
 3   cit_date     object 
 4   cit_name     object 
 5   cit_kind     object 
 6   cit_country  object 
 7   category     object 
 8   citseq       float64
 9   obsnum       float64
dtypes: float64(3), int64(2), object(5)
memory usage: 1.0+ GB


In [6]:
df.isnull().sum()

Unnamed: 0           0
patent               0
citation             0
cit_date             0
cit_name        269461
cit_kind       9279737
cit_country    9108887
category       9108887
citseq         9108887
obsnum               0
dtype: int64

In [7]:
df.shape

(14000000, 10)

In [8]:
df['cit_date'] = pd.to_datetime(df['cit_date'], errors='coerce')

In [9]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [10]:
df.head()

patent   citation   cit_date      cit_name cit_kind cit_country category   
0  6009555  4192017.0 1980-03-01           FAY      NaN         NaN      NaN  \
1  6009555  4547903.0 1985-10-01  BROWN ET AL.      NaN         NaN      NaN   
2  6009555  4768231.0 1988-09-01       SCHRACK      NaN         NaN      NaN   
3  6009555  4951316.0 1990-08-01         MOODY      NaN         NaN      NaN   
4  6009555  5105475.0 1992-04-01   LYND ET AL.      NaN         NaN      NaN   

   citseq  obsnum  
0     NaN     1.0  
1     NaN     2.0  
2     NaN     3.0  
3     NaN     4.0  
4     NaN     5.0

In [11]:
df["cit_name"].value_counts()

cit_name
LEE ET AL.         20863
LEE                19944
CHEN ET AL.        16961
SMITH              16318
SMITH ET AL.       15785
                   ...  
DE VROU                1
Sendzik                1
Levnig et al.          1
BEROWITZ ET AL.        1
Kamibayasi             1
Name: count, Length: 700684, dtype: int64

In [12]:
df["cit_name"].nunique()

700684

In [13]:
df["cit_name"].unique().tolist()

['FAY',
 'BROWN ET AL.',
 'SCHRACK',
 'MOODY',
 'LYND ET AL.',
 'WALKER',
 'POLACK',
 'CAMARENA',
 'JOSEPH',
 'SEHORN',
 'BEARD',
 'CHOW',
 'KUEHNER',
 'OTANI',
 'ANDREW',
 'RECTOR',
 'CHAPPELL, JR. ET AL.',
 'BANKS ET AL.',
 'MORRIS',
 'SWAN',
 'MAYE',
 'BLOCK',
 'CHEEK',
 'WILMOT',
 'GORDON',
 'WILLIAMS',
 'MESEK ET AL.',
 'WIDEMAN',
 'ALES ET AL.',
 'MORMAN',
 'VANDER WIELEN ET AL.',
 'BOLAND ET AL.',
 'MEYER ET AL.',
 'VAN GOMPEL ET AL.',
 'MESEK',
 'SUZUKI ET AL.',
 'PFLAUMER',
 'VON BLUCHER ET AL.',
 'BLUCHER ET AL.',
 'SESSELMANN',
 'BINGHAM ET AL.',
 'LESLEY',
 'MORTENSEN ET AL.',
 'ALDRIDGE',
 'LIGHTLE ET AL.',
 'BUTZER ET AL.',
 'LEWICKI',
 'RHEE',
 'JONES',
 'DE BARSY',
 'GWON',
 'BERGEE ET AL.',
 'HASEGAWA',
 'ADAMS, SR.',
 'NAVA ET AL.',
 'NAVA',
 'MATTSSON',
 'HUBER',
 'KAMIYA ET AL.',
 'MITCHELL ET AL.',
 'SCHNITZLER',
 'BORERSMA',
 'MITCHELL',
 'BROERSMA',
 'SUNDAHL',
 'ARAI',
 'KAWASAKI ET AL.',
 'FOHL',
 'CANTWELL ET AL.',
 'OKADA',
 'FRANO',
 'AILEO',
 'MIRAGE',
 'FL

In [14]:
check_nan = df['cit_name'].isnull().values.any()

In [15]:
check_nan

True

In [16]:
df["cit_name"].nunique()

700684

In [17]:
df['cit_name'].fillna(value= "Unspecified", inplace=True)

In [18]:
mean_value=df['cit_date'].mean()

df['cit_date'].fillna(value=mean_value, inplace=True)

In [19]:
df['cit_kind'].value_counts()

cit_kind
A     3544991
B1     982295
B2     106635
A1      63871
A2      15858
B        1580
C1       1478
A3        776
U1        707
C2        481
U         368
C         304
Y         260
A5        218
T2         99
T          46
Y2         40
M          36
A6         30
P          30
B4         16
C3         15
B3         13
A9         13
AB         12
S           9
A7          8
AA          7
T1          6
A0          5
E           5
C6          4
B9          4
S2          3
WO          3
A4          3
AZ          3
AO          3
SP          2
L           2
CA          2
B6          2
Z           2
AI          2
Y1          2
c           1
G           1
U0          1
Ab          1
T3          1
I           1
PN          1
Ba          1
BA          1
AE          1
BB          1
BI          1
A8          1
F1          1
Name: count, dtype: int64

In [20]:
df['cit_kind'].nunique()

59

In [21]:
df['cit_kind'].unique()

array([nan, 'A', 'B1', 'B2', 'A1', 'C2', 'A2', 'B', 'A3', 'A5', 'C', 'C1',
       'A6', 'U1', 'U', 'P', 'WO', 'T2', 'Y2', 'S', 'A9', 'Y', 'AB', 'T',
       'E', 'Ab', 'M', 'C3', 'AI', 'Y1', 'B4', 'AA', 'Z', 'AZ', 'C6',
       'B6', 'A8', 'B3', 'AO', 'Ba', 'A7', 'CA', 'c', 'L', 'SP', 'BI',
       'B9', 'BB', 'T1', 'AE', 'BA', 'PN', 'G', 'S2', 'A0', 'I', 'T3',
       'A4', 'U0', 'F1'], dtype=object)

In [22]:
df['cit_kind'].fillna(value= "UN", inplace=True)

In [23]:
df['cit_kind'].unique()

array(['UN', 'A', 'B1', 'B2', 'A1', 'C2', 'A2', 'B', 'A3', 'A5', 'C',
       'C1', 'A6', 'U1', 'U', 'P', 'WO', 'T2', 'Y2', 'S', 'A9', 'Y', 'AB',
       'T', 'E', 'Ab', 'M', 'C3', 'AI', 'Y1', 'B4', 'AA', 'Z', 'AZ', 'C6',
       'B6', 'A8', 'B3', 'AO', 'Ba', 'A7', 'CA', 'c', 'L', 'SP', 'BI',
       'B9', 'BB', 'T1', 'AE', 'BA', 'PN', 'G', 'S2', 'A0', 'I', 'T3',
       'A4', 'U0', 'F1'], dtype=object)

In [24]:
df['cit_country'].value_counts()

cit_country
US    4621850
JP      80669
EP      68255
DE      32774
GB      32238
       ...   
ZM          1
CM          1
FJ          1
SN          1
SL          1
Name: count, Length: 86, dtype: int64

In [25]:
df['cit_country'].nunique()

86

In [26]:
df['cit_country'].unique()

array([nan, 'US', 'CA', 'GB', 'FR', 'EP', 'WO', 'JP', 'TW', 'DE', 'CN',
       'AU', 'CH', 'KR', 'ES', 'SE', 'RO', 'RU', 'CZ', 'FI', 'SU', 'AT',
       'IT', 'NO', 'NL', 'DD', 'BE', 'HU', 'BG', 'BR', 'IL', 'NZ', 'DK',
       'ER', 'IR', 'PL', 'ZA', 'LU', 'YU', 'IE', 'DM', 'LV', 'IN', 'MX',
       'SK', 'DO', 'CS', 'ZM', 'PT', 'CL', 'SA', 'UA', 'EA', 'SG', 'GR',
       'OA', 'KP', 'MY', 'SN', 'IS', 'HK', 'SI', 'GP', 'SD', 'AR', 'TH',
       'GE', 'NR', 'FJ', 'CM', 'VE', 'BA', 'KE', 'MN', 'NE', 'JO', 'PH',
       'LR', 'CR', 'UY', 'MC', 'EE', 'PE', 'SO', 'BZ', 'SZ', 'SL'],
      dtype=object)

In [27]:
df['cit_country'].fillna(value= "UN", inplace=True)

In [28]:
df['citseq'].value_counts()

citseq
0.0      290608
1.0      279494
2.0      263865
3.0      245622
4.0      225824
          ...  
989.0         1
991.0         1
992.0         1
990.0         1
984.0         1
Name: count, Length: 993, dtype: int64

In [29]:
df['citseq'].nunique()

993

In [30]:
df['citseq'].unique()

array([ nan,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,
        10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,
        21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  38.,  29.,  37.,  39.,  40.,  41.,  42.,
        43.,  44.,  45.,  46.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
       253.,  47.,  48.,  56.,  57., 188.,  58.,  59.,  60.,  61.,  62.,
        63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71., 204.,  72.,
        73.,  74.,  75., 206.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,
        83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,
        94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102., 103., 104.,
       105., 106., 107., 108., 109., 110., 111., 112., 113., 115., 116.,
       117., 118., 119., 120., 121., 122., 123., 124., 125., 126., 127.,
       128., 129., 130., 131., 132., 133., 134., 135., 136., 137., 211.,
       214., 216., 176., 218., 219., 220., 180., 19

In [31]:
mean_value=df['citseq'].mean()

df['citseq'].fillna(value=mean_value, inplace=True)

In [32]:
df['category'].value_counts()

category
cited by other       3224756
cited by examiner    1666357
Name: count, dtype: int64

In [33]:
df['category'].nunique()

2

In [34]:
df['category'].unique()

array([nan, 'cited by examiner', 'cited by other'], dtype=object)

In [35]:
df['category'].fillna(value= "UN Specified", inplace=True)

In [36]:
# sns.heatmap(df.isnull(), cbar=False)

In [ ]:
df.to_csv('Citations_2.csv')