In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Patents_1975-2010.csv')

In [4]:
df.head()

Unnamed: 0   patent kind  claims  apptype  appnum       gdate  gyear   
0           0  3858241  NaN     6.0      NaN     NaN  1975-01-07   1975  \
1           1  3858242  NaN     5.0      NaN     NaN  1975-01-07   1975   
2           2  3858243  NaN    12.0      NaN     NaN  1975-01-07   1975   
3           3  3858244  NaN     1.0      NaN     NaN  1975-01-07   1975   
4           4  3858245  NaN     5.0      NaN     NaN  1975-01-07   1975   

      appdate  appyear  
0  1974-03-26   1974.0  
1  1973-04-16   1973.0  
2  1973-07-11   1973.0  
3  1973-12-17   1973.0  
4  1972-05-18   1972.0

In [5]:
df.shape

(3984771, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3984771 entries, 0 to 3984770
Data columns (total 10 columns):
 #   Column      Dtype  
---  ------      -----  
 0   Unnamed: 0  int64  
 1   patent      int64  
 2   kind        object 
 3   claims      float64
 4   apptype     float64
 5   appnum      float64
 6   gdate       object 
 7   gyear       int64  
 8   appdate     object 
 9   appyear     float64
dtypes: float64(4), int64(3), object(3)
memory usage: 304.0+ MB


In [7]:
df.isnull().sum()

Unnamed: 0          0
patent              0
kind          2302931
claims           1763
apptype       1841665
appnum        1838309
gdate               0
gyear               0
appdate             2
appyear             2
dtype: int64

In [8]:
df.drop(columns=['Unnamed: 0',], axis=1, inplace=True)

In [9]:
df.head()

patent kind  claims  apptype  appnum       gdate  gyear     appdate   
0  3858241  NaN     6.0      NaN     NaN  1975-01-07   1975  1974-03-26  \
1  3858242  NaN     5.0      NaN     NaN  1975-01-07   1975  1973-04-16   
2  3858243  NaN    12.0      NaN     NaN  1975-01-07   1975  1973-07-11   
3  3858244  NaN     1.0      NaN     NaN  1975-01-07   1975  1973-12-17   
4  3858245  NaN     5.0      NaN     NaN  1975-01-07   1975  1972-05-18   

   appyear  
0   1974.0  
1   1973.0  
2   1973.0  
3   1973.0  
4   1972.0

In [10]:
df['patent'].value_counts()

patent
3858241    1
6528317    1
6528289    1
6528290    1
6528291    1
          ..
5188996    1
5188997    1
5188998    1
5188999    1
7788732    1
Name: count, Length: 3984771, dtype: int64

In [11]:
df['patent'].nunique()

3984771

In [12]:
df['kind'].value_counts()

kind
B2    1119954
B1     561885
A1          1
Name: count, dtype: int64

In [13]:
df['kind'].nunique()

3

In [14]:
df['kind'].unique()

array([nan, 'B1', 'B2', 'A1'], dtype=object)

In [15]:
df['kind'].fillna(value= "U1", inplace=True)

In [16]:
df['claims'].value_counts()

claims
6.0      211507
8.0      207149
10.0     202768
7.0      194459
5.0      188456
          ...  
390.0         1
383.0         1
496.0         1
665.0         1
520.0         1
Name: count, Length: 366, dtype: int64

In [17]:
df['claims'].nunique()

366

In [18]:
df['claims'].unique()

array([  6.,   5.,  12.,   1.,   4.,  17.,   2.,   3.,  10.,   8.,  16.,
        11.,  19.,   9.,  24.,  14.,  13.,  23.,  21.,  20.,  22.,   7.,
        15.,  30.,  35.,  28.,  18.,  57.,  36.,  25.,  51.,  26.,  34.,
        33.,  37.,  27.,  31.,  67.,  29.,  nan,  47.,  32.,  72.,  43.,
        38.,  46.,  41.,  45.,  59.,  39.,  40.,  80.,  42.,  44.,  53.,
        63.,  61.,  55.,  62.,  49.,  50., 104.,  81.,  73., 127.,  56.,
        60.,  76.,  58.,  79.,  85.,  74.,  48.,  68., 101.,  65.,  86.,
        66.,  75.,  78.,  97.,  54.,  70.,  52., 103., 111.,  83., 108.,
       115.,  88., 147.,  69.,  64., 176., 119., 139.,  91., 112., 109.,
        71.,  93., 135.,  98., 132.,  96.,  82., 212., 160.,  87., 106.,
       218.,  94., 140., 128.,  89., 122., 260.,  84., 116.,  77., 105.,
       136.,  92., 120., 141., 148.,  90., 100., 102.,  95., 133., 154.,
       226.,  99., 195., 393., 124., 472., 175., 706., 110., 153., 211.,
       254., 131., 152., 145., 146., 134., 113., 11

In [19]:
b= df['claims'].isnull().values.any()

In [20]:
b

True

In [21]:
mean_value=df['claims'].mean()

df['claims'].fillna(value=mean_value, inplace=True)

In [22]:
df['apptype'].value_counts()

apptype
10.0    612743
9.0     564104
1.0     461266
11.0    409480
12.0     65911
8.0      28781
7.0        640
6.0         92
5.0         59
4.0         18
3.0          8
2.0          4
Name: count, dtype: int64

In [23]:
df['apptype'].nunique()

12

In [24]:
df['apptype'].unique()

array([nan,  8.,  1.,  7.,  9.,  4.,  2.,  6.,  5.,  3., 10., 11., 12.])

In [25]:
mean_value=df['apptype'].mean()

df['apptype'].fillna(value=mean_value, inplace=True)

In [26]:
df['appnum'].unique()

array([      nan,  8634532.,  7357958., ..., 11333452., 11089818.,
       11726590.])

In [27]:
mean_value=df['appnum'].mean()

df['appnum'].fillna(value=mean_value, inplace=True)

In [28]:
df['gdate'] = pd.to_datetime(df['gdate'], errors='coerce')

In [29]:
df['gdate'].nunique()

1879

In [30]:
df['gdate'].unique()

<DatetimeArray>
['1975-01-07 00:00:00', '1975-01-14 00:00:00', '1975-01-21 00:00:00',
 '1975-01-28 00:00:00', '1975-02-04 00:00:00', '1975-02-11 00:00:00',
 '1975-02-18 00:00:00', '1975-02-25 00:00:00', '1975-03-04 00:00:00',
 '1975-03-11 00:00:00',
 ...
 '2010-06-22 00:00:00', '2010-06-01 00:00:00', '2010-02-23 00:00:00',
 '2010-09-28 00:00:00', '2010-07-27 00:00:00', '2010-05-04 00:00:00',
 '2010-02-02 00:00:00', '2010-03-02 00:00:00', '2010-01-26 00:00:00',
 '2010-08-31 00:00:00']
Length: 1879, dtype: datetime64[ns]

In [31]:
x = df['gdate'].isnull().values.any()

In [32]:
x

False

In [33]:
df['gyear'].value_counts()

gyear
2010    219909
2006    173922
2003    169105
2009    167537
2002    167424
2001    166065
2004    164413
2008    157894
2000    157596
2007    157502
1999    153593
1998    147574
2005    143927
1997    111984
1996    109645
1994    101676
1995    101419
1993     98342
1992     97444
1991     96513
1989     95537
1990     90364
1987     82952
1988     77924
1975     72000
1985     71661
1986     70860
1976     70226
1984     67200
1978     66102
1981     65771
1977     65269
1980     61819
1982     57888
1983     56860
1979     48854
Name: count, dtype: int64

In [34]:
df['gyear'].nunique()

36

In [35]:
df['gyear'].unique()

array([1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985,
       1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996,
       1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007,
       2008, 2009, 2010], dtype=int64)

In [36]:
y = df['gyear'].isnull().values.any()

In [37]:
y

False

In [38]:
df['appdate'] = pd.to_datetime(df['appdate'], errors='coerce')

In [39]:
df['appdate'].dtypes

dtype('<M8[ns]')

In [40]:
z = df['appdate'].isnull().values.any()

In [41]:
z

True

In [42]:
mean_value=df['appdate'].mean()

df['appdate'].fillna(value=mean_value, inplace=True)

In [43]:
df['appyear'].value_counts()

appyear
2001.0    208908
2002.0    206229
2000.0    196639
2003.0    191514
2004.0    181840
           ...  
1905.0         1
1921.0         1
1915.0         1
1929.0         1
1922.0         1
Name: count, Length: 90, dtype: int64

In [44]:
df['appyear'].nunique()

90

In [45]:
df['appyear'].unique()

array([1974., 1973., 1972., 1971., 1970., 1969., 1965., 1960., 1961.,
       1967., 1966., 1968., 1963., 1959., 1957., 1964., 1954., 1958.,
       1962., 1975., 1955., 1956., 1944., 1942., 1953., 1950., 1945.,
       1946., 1943., 1952.,   nan, 1949., 1948., 1976., 1941., 1951.,
       1925., 1977., 1978., 1940., 1938., 1979., 1936., 1947., 1980.,
       1981., 1982., 1983., 1984., 1922., 1904., 1985., 1930., 1986.,
       1987., 1988., 1989., 1990., 1931., 1908., 1918., 1939., 1991.,
       1992., 1921., 1901., 1993., 1902., 1909., 1903., 1994., 1929.,
       1915., 1995., 1996., 1905., 1997., 1998., 1999., 2000., 1933.,
       2001., 2002., 2003., 2004., 2005., 2006., 2007., 2008., 2009.,
       2010.])

In [46]:
r = df['appyear'].isnull().values.any()

In [47]:
r

True

In [48]:
mean_value=df['appyear'].mean()

mean_value

1994.0293628062254

In [49]:
df['appyear'] = pd.to_numeric(df['appyear'], errors='coerce').fillna(1994, downcast='infer')

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3984771 entries, 0 to 3984770
Data columns (total 9 columns):
 #   Column   Dtype         
---  ------   -----         
 0   patent   int64         
 1   kind     object        
 2   claims   float64       
 3   apptype  float64       
 4   appnum   float64       
 5   gdate    datetime64[ns]
 6   gyear    int64         
 7   appdate  datetime64[ns]
 8   appyear  int64         
dtypes: datetime64[ns](2), float64(3), int64(3), object(1)
memory usage: 273.6+ MB


In [51]:
df.isnull().sum()

patent     0
kind       0
claims     0
apptype    0
appnum     0
gdate      0
gyear      0
appdate    0
appyear    0
dtype: int64

In [52]:
df.to_csv('Patents.csv')