In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('Citations_1975-1999.csv')

In [4]:
df.head()

Unnamed: 0  citation   patent cit_date cit_name  cit_kind  cit_country   
0           0    956203  3858241      NaN      NaN       NaN          NaN  \
1           1   1324234  3858241      NaN      NaN       NaN          NaN   
2           2   1515701  3858242      NaN      NaN       NaN          NaN   
3           3   3319261  3858242      NaN      NaN       NaN          NaN   
4           4   3681785  3858243      NaN      NaN       NaN          NaN   

   category  citseq  cites  
0       NaN     0.0    1.0  
1       NaN     1.0    2.0  
2       NaN     0.0    1.0  
3       NaN     1.0    3.0  
4       NaN     5.0    8.0

In [5]:
df.shape

(3207647, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3207647 entries, 0 to 3207646
Data columns (total 10 columns):
 #   Column       Dtype  
---  ------       -----  
 0   Unnamed: 0   int64  
 1   citation     int64  
 2   patent       int64  
 3   cit_date     object 
 4   cit_name     object 
 5   cit_kind     float64
 6   cit_country  float64
 7   category     float64
 8   citseq       float64
 9   cites        float64
dtypes: float64(5), int64(3), object(2)
memory usage: 244.7+ MB


In [7]:
df.isna().sum()

Unnamed: 0           0
citation             0
patent               0
cit_date       2708833
cit_name       2708850
cit_kind       3207647
cit_country    3207647
category       3207647
citseq          498814
cites                0
dtype: int64

In [8]:
# sns.heatmap(df.isnull(), cbar=False)

In [9]:
df.drop(columns=['Unnamed: 0', 'cit_kind','cit_country','category'], axis=1, inplace=True)

In [10]:
df.head()

citation   patent cit_date cit_name  citseq  cites
0    956203  3858241      NaN      NaN     0.0    1.0
1   1324234  3858241      NaN      NaN     1.0    2.0
2   1515701  3858242      NaN      NaN     0.0    1.0
3   3319261  3858242      NaN      NaN     1.0    3.0
4   3681785  3858243      NaN      NaN     5.0    8.0

In [11]:
df['citation'].value_counts()

citation
956203     1
4396856    1
3921199    1
4538166    1
5111264    1
          ..
2399255    1
2349450    1
4457175    1
3508436    1
5048064    1
Name: count, Length: 3207647, dtype: int64

In [12]:
df['citation'].nunique()

3207647

In [13]:
df['citation'].unique()

array([ 956203, 1324234, 1515701, ..., 5598422, 4486882, 5048064],
      dtype=int64)

In [14]:
df['patent'].value_counts()

patent
5981719    118
5876995    101
5666776     96
5611186     79
5462324     75
          ... 
4472487      1
5289393      1
5289394      1
4472482      1
6009554      1
Name: count, Length: 1392766, dtype: int64

In [15]:
df['patent'].nunique()

1392766

In [16]:
df['patent'].unique()

array([3858241, 3858242, 3858243, ..., 6009551, 6009552, 6009554],
      dtype=int64)

In [17]:
df['cit_date'].value_counts()

cit_date
1996-07-01    6553
1996-12-01    6412
1996-10-01    6151
1996-04-01    5966
1997-04-01    5808
              ... 
1999-06-01     256
1979-06-01     224
1999-07-01     151
1999-08-01      75
1999-09-01      16
Name: count, Length: 297, dtype: int64

In [18]:
df['cit_date'].nunique()

297

In [19]:
df['cit_date'].unique()

array([nan, '1994-09-01', '1991-07-01', '1989-05-01', '1987-03-01',
       '1995-06-01', '1996-02-01', '1992-06-01', '1993-08-01',
       '1992-03-01', '1986-10-01', '1995-02-01', '1995-10-01',
       '1995-03-01', '1997-05-01', '1987-02-01', '1975-12-01',
       '1991-02-01', '1997-04-01', '1995-01-01', '1990-03-01',
       '1993-01-01', '1990-10-01', '1990-05-01', '1994-01-01',
       '1996-01-01', '1988-12-01', '1987-10-01', '1995-12-01',
       '1991-04-01', '1991-10-01', '1990-09-01', '1996-12-01',
       '1983-06-01', '1994-10-01', '1996-06-01', '1996-05-01',
       '1990-06-01', '1991-09-01', '1993-10-01', '1989-07-01',
       '1992-07-01', '1994-08-01', '1992-12-01', '1988-01-01',
       '1988-07-01', '1995-05-01', '1990-08-01', '1992-02-01',
       '1994-12-01', '1989-09-01', '1996-07-01', '1996-03-01',
       '1992-01-01', '1994-04-01', '1997-03-01', '1995-07-01',
       '1994-06-01', '1993-06-01', '1988-09-01', '1988-10-01',
       '1992-10-01', '1990-11-01', '1993-07-01', '

In [20]:
df['cit_date'] =  pd.to_datetime(df['cit_date'])

In [21]:
df['cit_date']

0                NaT
1                NaT
2                NaT
3                NaT
4                NaT
             ...    
3207642   1998-09-01
3207643   1998-05-01
3207644   1997-01-01
3207645   1984-12-01
3207646   1991-09-01
Name: cit_date, Length: 3207647, dtype: datetime64[ns]

In [22]:
mean_value=df['cit_date'].mean()

df['cit_date'].fillna(value=mean_value, inplace=True)

In [23]:
df['cit_date'].unique()

<DatetimeArray>
['1992-07-25 04:59:24.390734592',           '1994-09-01 00:00:00',
           '1991-07-01 00:00:00',           '1989-05-01 00:00:00',
           '1987-03-01 00:00:00',           '1995-06-01 00:00:00',
           '1996-02-01 00:00:00',           '1992-06-01 00:00:00',
           '1993-08-01 00:00:00',           '1992-03-01 00:00:00',
 ...
           '1998-12-01 00:00:00',           '1999-01-01 00:00:00',
           '1999-02-01 00:00:00',           '1999-03-01 00:00:00',
           '1999-04-01 00:00:00',           '1999-05-01 00:00:00',
           '1999-07-01 00:00:00',           '1999-06-01 00:00:00',
           '1999-08-01 00:00:00',           '1999-09-01 00:00:00']
Length: 298, dtype: datetime64[ns]

In [24]:
df['cit_date']

0         1992-07-25 04:59:24.390734592
1         1992-07-25 04:59:24.390734592
2         1992-07-25 04:59:24.390734592
3         1992-07-25 04:59:24.390734592
4         1992-07-25 04:59:24.390734592
                       ...             
3207642   1998-09-01 00:00:00.000000000
3207643   1998-05-01 00:00:00.000000000
3207644   1997-01-01 00:00:00.000000000
3207645   1984-12-01 00:00:00.000000000
3207646   1991-09-01 00:00:00.000000000
Name: cit_date, Length: 3207647, dtype: datetime64[ns]

In [25]:
df['cit_name'].value_counts()

cit_name
LEE              1174
SMITH             982
LEE ET AL.        920
SUZUKI ET AL.     833
SMITH ET AL.      772
                 ... 
HEFTI               1
CONANAN             1
CASCIO              1
HUJINK              1
PIRET ET AL.        1
Name: count, Length: 147982, dtype: int64

In [26]:
df['cit_name'].nunique()

147982

In [27]:
df['cit_name'].unique()

array([nan, 'GARRETT', 'HETZ ET AL.', ..., 'HELBIG, SR. ET AL.',
       'FITINGOF ET AL.', 'PIRET ET AL.'], dtype=object)

In [28]:
df['cit_name'].fillna(value="Unspecified", inplace=True)

In [29]:
df['citseq'].nunique()

364

In [30]:
df['citseq'].unique()

array([  0.,   1.,   5.,   2.,   3.,   4.,   7.,   8.,   9.,  10.,   6.,
        13.,  11.,  14.,  15.,  20.,  22.,  12.,  16.,  18.,  17.,  21.,
        19.,  28.,  27.,  32.,  34.,  29.,  24.,  23.,  25.,  31.,  26.,
        37.,  40.,  36.,  30.,  33.,  43.,  48.,  46.,  52.,  41.,  35.,
        39.,  42.,  66.,  58.,  38.,  45.,  69.,  64.,  63.,  51.,  54.,
        57.,  47.,  56.,  53.,  50.,  86.,  59.,  60.,  55.,  49.,  44.,
        72.,  61.,  70.,  76.,  62.,  71.,  68.,  65.,  67.,  77.,  75.,
        89.,  97.,  79.,  78.,  91.,  84.,  83., 101.,  92.,  85.,  82.,
        81.,  73., 100.,  99.,  74.,  95.,  93.,  80.,  94.,  98., 107.,
       115.,  96., 123.,  87., 114., 116.,  90., 111., 121., 117., 138.,
       118., 112., 129.,  88., 136., 109., 102., 108., 104., 120., 133.,
       113., 110., 158., 103., 128., 151., 144., 146., 122., 105., 119.,
       124., 125., 143., 106., 149., 137., 131., 140., 130., 139., 126.,
       195., 186., 148., 142., 153., 156., 135., 16

In [31]:
mean_value=df['citseq'].mean()

df['citseq'].fillna(value=mean_value, inplace=True)

In [32]:
df['cites'].nunique()

251

In [33]:
df['cites'].unique()

array([  1.,   2.,   3.,   8.,   4.,   7.,  11.,   5.,  12.,   6.,   9.,
        15.,  13.,  10.,  17.,  14.,  16.,  30.,  36.,  39.,  29.,  18.,
        19.,  35.,  27.,  23.,  33.,  21.,  41.,  28.,  62.,  22.,  26.,
        24.,  25.,  20.,  46.,  32.,  31.,  69.,  67.,  73.,  49.,  43.,
        40.,  34.,  59.,  38.,  65.,  58.,  48.,  50., 107.,  55., 105.,
        42.,  89.,  37.,  47.,  54.,  44.,  91.,  51.,  60., 118.,  45.,
        81.,  80.,  66.,  76.,  72.,  61., 119.,  56.,  63.,  53.,  75.,
       111.,  90.,  52., 153.,  93., 110.,  57., 125.,  68.,  70.,  99.,
       144., 114.,  83., 109.,  74.,  85.,  71.,  77.,  92.,  78.,  87.,
       276.,  88., 104.,  64., 100., 112., 115., 160.,  86.,  84., 156.,
       177., 138., 103., 132., 121., 117., 124.,  94.,  97., 108., 191.,
        95.,  79.,  82., 243., 279., 140., 141.,  98., 193., 152., 116.,
       113., 130., 180.,  96., 170., 146., 102., 216., 192., 122., 133.,
       139., 158., 129., 150., 106., 261., 128., 23

In [34]:
df['cites'].value_counts()

cites
1.0      921892
2.0      547939
3.0      374677
4.0      272947
5.0      205949
          ...  
194.0         1
714.0         1
232.0         1
207.0         1
219.0         1
Name: count, Length: 251, dtype: int64

In [35]:
df.isnull().sum()

citation    0
patent      0
cit_date    0
cit_name    0
citseq      0
cites       0
dtype: int64

In [36]:
 # sns.heatmap(df.isnull(), cbar=False)

In [37]:
df.to_csv('Citations_1.csv')